#!/usr/bin/env python3
"""
render_manuscript.py — Render manuscript chunks to a single markdown file.

Walks an ordered subset of chunks from manuscript_chunks.jsonl, resolves
placeholder defaults, numbers citations in first-appearance order, and
emits a unified Methods + Results + Discussion + References document.

Mirrors page 12's compose pipeline server-side so the same draft can be
produced from CI or a make target. Per-chunk overrides typed on page 12
live in localStorage and are NOT visible here; this script renders the
canonical defaults.

Usage:
    python3 -m toolkit_registries.scripts.render_manuscript [--out PATH] [--manifest PATH]

If --manifest is omitted, the built-in DEFAULT_MANIFEST is used (covers
the MS_Inversions LG01 × LG28 + LG27 manuscript-track arc).
"""
from __future__ import annotations
import argparse
import json
import pathlib
import re
import sys

REPO    = pathlib.Path(__file__).resolve().parents[2]
REG     = REPO / "toolkit_registries" / "relatedness" / "01_registry"

# Curated manuscript-track chunk arc. Order matters: cites appear in first-
# appearance order, so this drives the bibliography numbering too.
DEFAULT_MANIFEST = [
    # ------ Methods ------
    "methods.cross_species_breakpoints",
    "methods.iv_candidate_promoter",
    "methods.karyotype_auto_caller",
    "methods.karyotype_polarizer",
    "methods.relatedness_ngsrelate",
    "methods.pedigree_ngspedigree",
    "methods.mendelian_path_a",
    "methods.popstats_groupwise",
    "methods.inversion_pair_incompatibility",
    "methods.meiosis_interchromosomal",
    # ------ Results ------
    "results.lg27_bounded_inversion",
    "results.lg28_recurrent",
    "results.inversion_candidate_summary",
    "results.karyotype_distribution_lg28",
    "results.path_a_mendelian",
    "results.inversion_pair_incompatibility",
    # ------ Discussion ------
    "discussion.lg01_lg28_pair_relation",
    "discussion.cross_species_handoff",
]


def load_jsonl(p: pathlib.Path) -> list[dict]:
    return [json.loads(l) for l in p.read_text().splitlines() if l.strip()]


def resolve_default(chunk: dict, name: str) -> str:
    """Page-12 server-side equivalent of resolvePlaceholder() with no scope
    + no localStorage override. Falls back to the chunk's declared default."""
    spec = (chunk.get("placeholders") or {}).get(name) or {}
    return str(spec.get("default", f"{{{{{name}}}}}"))


def apply_template(chunk: dict) -> str:
    tpl = chunk.get("template", "")
    return re.sub(r"\{\{([a-zA-Z0-9_]+)\}\}", lambda m: resolve_default(chunk, m.group(1)), tpl)


def collect_refs(chunk: dict) -> list[str]:
    """Both declared + inline [@RefId] cites, in declaration-then-body order."""
    out: list[str] = []
    seen: set[str] = set()
    for r in (chunk.get("references") or []):
        if r not in seen:
            out.append(r); seen.add(r)
    for m in re.finditer(r"\[@([A-Za-z][A-Za-z0-9_]*)\]", chunk.get("template", "")):
        r = m.group(1)
        if r not in seen:
            out.append(r); seen.add(r)
    return out


def render(manifest: list[str], chunks_by_id: dict, refs_by_id: dict) -> str:
    cite_order: list[str] = []
    index_of: dict[str, int] = {}
    by_section: dict[str, list[tuple[dict, str]]] = {"methods": [], "results": [], "discussion": []}

    # First pass: assign citation indices in first-appearance order
    for cid in manifest:
        c = chunks_by_id.get(cid)
        if not c:
            print(f"  ! unknown chunk_id in manifest: {cid}", file=sys.stderr)
            continue
        for r in collect_refs(c):
            if r not in index_of:
                index_of[r] = len(cite_order) + 1
                cite_order.append(r)
        sec = c.get("section", "methods")
        by_section.setdefault(sec, []).append((c, apply_template(c)))

    # Second pass: render
    out: list[str] = []
    out.append("# MS_Inversions — assembled manuscript draft v0\n")
    out.append("*Generated by `toolkit_registries/scripts/render_manuscript.py` "
               "from `manuscript_chunks.jsonl` (canonical defaults; per-user "
               "edits on page 12 not included).*\n")
    out.append(f"*Cohort: 226-sample Clarias gariepinus hatchery, reference fClaHyb_Gar_LG. "
               f"Manuscript-track arc: LG01 × LG28 pair-relation + LG27 cross-species bounded inversion.*\n")

    for section in ("methods", "results", "discussion"):
        if not by_section.get(section):
            continue
        out.append(f"\n## {section.capitalize()}\n")
        for chunk, body in by_section[section]:
            txt = body
            # Inline [@RefId] → [n]; declared refs not cited inline get appended pre-period
            txt = re.sub(r"\[@([A-Za-z][A-Za-z0-9_]*)\]",
                         lambda m: f"[{index_of[m.group(1)]}]" if m.group(1) in index_of else m.group(0),
                         txt)
            inline = set(re.findall(r"\[@([A-Za-z][A-Za-z0-9_]*)\]", chunk.get("template", "")))
            trailing = [f"[{index_of[r]}]" for r in collect_refs(chunk)
                        if r not in inline and r in index_of]
            if trailing:
                lp = txt.rfind(".")
                ins = " " + "".join(trailing)
                txt = txt[:lp] + ins + txt[lp:] if lp >= 0 else txt + ins
            out.append(f"**{chunk.get('label', chunk['chunk_id'])}** — {txt}\n")

    if cite_order:
        out.append("\n## References\n")
        for i, rid in enumerate(cite_order, start=1):
            r = refs_by_id.get(rid)
            if not r:
                out.append(f"{i}. _{rid}_ — not in references.jsonl\n")
                continue
            tail = ""
            if r.get("doi"):
                tail = f" doi:{r['doi']}"
            elif r.get("url"):
                tail = f" {r['url']}"
            out.append(f"{i}. {r['citation']}{tail}\n")

    return "\n".join(out) + "\n"


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Render manuscript chunks to a markdown draft.")
    ap.add_argument("--out", default=str(REPO / "MANUSCRIPT_DRAFT_v0.md"))
    ap.add_argument("--manifest", default="", help="Optional path to a newline-separated list of chunk_ids to include.")
    args = ap.parse_args(argv)

    chunks = load_jsonl(REG / "manuscript_chunks.jsonl")
    refs   = load_jsonl(REG / "references.jsonl")
    chunks_by_id = {c["chunk_id"]: c for c in chunks}
    refs_by_id   = {r["ref_id"]: r   for r in refs}

    if args.manifest:
        manifest = [l.strip() for l in pathlib.Path(args.manifest).read_text().splitlines() if l.strip() and not l.startswith("#")]
    else:
        manifest = DEFAULT_MANIFEST

    md = render(manifest, chunks_by_id, refs_by_id)
    out = pathlib.Path(args.out)
    out.write_text(md)
    print(f"  wrote {out}  ({len(md)} chars, {len(manifest)} chunks)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
