#!/usr/bin/env python3
"""
check_plans.py — validate panel_plan_v1 files against the live registry.

Walks every file under 02_queue/plans/ matching plan_*.json (including
plan_auto_*.json and plan_*.example.json) and verifies:

  1. schema_version == "panel_plan_v1"
  2. Every step.panel_id is either:
       - registered in panels.jsonl, OR
       - matches the auto-generated <layer>_card / <layer>_picker
         convention from lib.plan_generator (a separate enum of allowed
         conventional names; flagged as "convention" not "registered")
  3. Every step.from_analysis is in analysis_registry
  4. Every step.expects_layers value is in layer_registry
  5. Every step.gates_status[*].graph is one of the 5 registered graphs
     (vocab_graph, layer_graph, chain_graph, scope_graph,
     atlas_dependency_graph)
  6. Every step.gates_status[*].node references a real entity in its
     declared graph (loose check — full graph-walk lands when
     panel_coverage_graph is wired)
  7. The plan's index.json entry matches the plan file's plan_id

Exit code: 0 if clean; 1 if any check fails. Used by smoke_all_stack.
"""
from __future__ import annotations
import json
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parents[3]
REG  = REPO / "toolkit_registries" / "relatedness" / "01_registry"
PQ   = REPO / "toolkit_registries" / "relatedness" / "02_queue" / "plans"

REGISTERED_GRAPHS = {"vocab_graph", "layer_graph", "chain_graph", "scope_graph", "atlas_dependency_graph"}


def load_jsonl(p: pathlib.Path) -> list[dict]:
    if not p.exists(): return []
    return [json.loads(l) for l in p.read_text().splitlines() if l.strip()]


def is_conventional_panel_id(pid: str) -> bool:
    # Auto-generated by lib.plan_generator from layer_ids
    return bool(re.match(r"^[a-z][a-z0-9_]+_(card|picker|panel|table|chart)$", pid)) \
        or pid in {"next_action_proposal", "manuscript_chunks_panel"}


def check_plan(plan_path: pathlib.Path, panels: set, analyses: set, layers: set) -> list[str]:
    errs: list[str] = []
    name = plan_path.name
    try:
        plan = json.loads(plan_path.read_text())
    except Exception as e:
        return [f"{name}: failed to parse: {e}"]

    if plan.get("schema_version") != "panel_plan_v1":
        errs.append(f"{name}: schema_version != 'panel_plan_v1' (got {plan.get('schema_version')!r})")

    pid = plan.get("plan_id")
    if not pid:
        errs.append(f"{name}: missing plan_id")

    for i, step in enumerate(plan.get("steps", [])):
        loc = f"{name}:step[{i}]"
        ppid = step.get("panel_id")
        if not ppid:
            errs.append(f"{loc}: missing panel_id")
        elif ppid not in panels and not is_conventional_panel_id(ppid):
            errs.append(f"{loc}: panel_id {ppid!r} neither registered nor conventional")
        fa = step.get("from_analysis")
        if fa and fa not in analyses:
            errs.append(f"{loc}: from_analysis {fa!r} not in analysis_registry")
        for L in step.get("expects_layers", []) or []:
            if L not in layers:
                errs.append(f"{loc}: expects_layers item {L!r} not in layer_registry")
        for j, g in enumerate(step.get("gates_status", []) or []):
            gr = g.get("graph")
            if gr not in REGISTERED_GRAPHS:
                errs.append(f"{loc}.gate[{j}]: graph {gr!r} not in {sorted(REGISTERED_GRAPHS)}")
            node = g.get("node") or g.get("path")
            if not node:
                errs.append(f"{loc}.gate[{j}]: missing node/path")
        for j, a in enumerate(step.get("actions", []) or []):
            for k, ag in enumerate(a.get("gates_status", []) or []):
                if ag.get("graph") not in REGISTERED_GRAPHS:
                    errs.append(f"{loc}.action[{j}].gate[{k}]: graph {ag.get('graph')!r} not registered")

    return errs


def check_index(idx_path: pathlib.Path, plan_ids_on_disk: set) -> list[str]:
    errs: list[str] = []
    if not idx_path.exists():
        return errs  # absent index is fine; page 14 falls back to *.example.*
    try:
        idx = json.loads(idx_path.read_text())
    except Exception as e:
        return [f"{idx_path.name}: failed to parse: {e}"]
    if idx.get("schema_version") != "queue_plan_index_v1":
        errs.append(f"{idx_path.name}: schema_version != 'queue_plan_index_v1'")
    declared = {e["plan_id"] for e in idx.get("entries", [])}
    missing = declared - plan_ids_on_disk
    if missing:
        errs.append(f"{idx_path.name}: lists {len(missing)} plan_id(s) not on disk: {sorted(missing)[:5]}…")
    orphan = plan_ids_on_disk - declared
    if orphan:
        errs.append(f"{idx_path.name}: {len(orphan)} plan file(s) on disk not in index: {sorted(orphan)[:5]}…")
    return errs


def main(argv: list[str] | None = None) -> int:
    panels   = {p["panel_id"]      for p in load_jsonl(REG / "panels.jsonl")}
    analyses = {a["analysis_id"]   for a in load_jsonl(REG / "analysis_registry.jsonl")}
    layers   = {L["layer_id"]      for L in load_jsonl(REG / "layer_registry.jsonl")}

    if not PQ.exists():
        print("OK    no 02_queue/plans/ — nothing to check")
        return 0

    plan_files = sorted(p for p in PQ.glob("plan_*.json") if p.is_file())
    if not plan_files:
        print("OK    no plan files under 02_queue/plans/")
        return 0

    all_errs: list[str] = []
    plan_ids_on_disk: set = set()
    for f in plan_files:
        errs = check_plan(f, panels, analyses, layers)
        all_errs.extend(errs)
        try:
            plan_ids_on_disk.add(json.loads(f.read_text()).get("plan_id"))
        except Exception:
            pass

    # Index cross-check (live index only; example index can drift safely)
    all_errs.extend(check_index(PQ / "index.json", plan_ids_on_disk))

    if all_errs:
        print(f"FAIL  {len(all_errs)} problem(s) across {len(plan_files)} plan file(s):")
        for e in all_errs[:50]:
            print(f"  - {e}")
        if len(all_errs) > 50:
            print(f"  ... and {len(all_errs) - 50} more")
        return 1

    print(f"OK    {len(plan_files)} plan file(s) clean")
    return 0


if __name__ == "__main__":
    sys.exit(main())
